name: Tests

on: [push,]

jobs:

  run_tests:
    name:  Run  on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-18.04
            python: 3.9
          - os: windows-latest
            python: 3.9
          - os: macos-latest
            python: 3.9
    steps:
      - uses: actions/setup-python@v2
        name: Install Python ${{ matrix.python }}
        with:
          python-version: ${{ matrix.python }}

      - name: Set output in default shell
        id: default_shell
        run: echo "::set-output name=out::$(python -c 'print(""HELLO"")')"

      - name: Run an action using a python shell
        id: python_shell
        shell: python
        run: |
          import sys
          print(sys.version)
          print("::set-output name=out::%s" % sys.version)

      - name: Print results
        run: |
          echo "${{ steps.default_shell.outputs.out }}"
          echo "${{ steps.python_shell.outputs.out }}"
